# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_boughtgames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtgames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Game'),
        ),
        migrations.AlterField(
            model_name='boughtgames',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
