# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180213_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
